### ISSUE TITLE
[BUG] Blank page in submit profiling

### ISSUE THREAD

**Issue by jian-he** [kubedl-io/morphling#29]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

http://localhost:7070/pe-submit shows blank page 

**What did you expect to happen:**

**Anything else we need to know?**:

**Environment:**
- Morphling version:
- Minikube version (`minikube version`):
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lwangbm** [comment]
The pe-submit page seems to work well in my environment (in both yaml and helm installations). 

If pe-sumit page is the only page that is blank, I suspect  the reason is that, the configmap (name: morphling-data-config, namespace: morphling-system) is not created, which provides default content in the pe-submission form.

**Comment by lwangbm** [comment]
> **What steps did you take and what happened:**
> [A clear and concise description of what the bug is.]
> 
> http://localhost:7070/pe-submit shows blank page
> 
> **What did you expect to happen:**
> 
> **Anything else we need to know?**:
> 
> **Environment:**
> 
> * Morphling version:
> * Minikube version (`minikube version`):
> * Kubernetes version (use `kubectl version`):
> * OS (e.g: `cat /etc/os-release`):
> * Kernel (e.g. `uname -a`):
> * Install tools:
> * Others:

The pe-submit page seems to work well in my environment (in both yaml and helm installations).

If pe-sumit page is the only page that is blank, I suspect the reason is that, the configmap (name: morphling-data-config, namespace: morphling-system) is not created, which provides default content in the pe-submission form.

**Comment by lwangbm** [comment]
fixed in https://github.com/kubedl-io/morphling/pull/35

**Comment by lwangbm** [comment]
will close this issue
